### ISSUE TITLE
Flatpaks on CachyOS Paclkage Installer

### ISSUE THREAD

**Issue by elajil** [CachyOS/packageinstaller#1]
When i try to add flatpaks service in "CachyOS Package Installer" i get error "Flatpak was to installed"
Console output:

```
Pakiet (6)                       Nowa wersja  Zmiana    Do pobrania

extra/bubblewrap                 0.8.0-1      0,08 MiB     0,04 MiB
cachyos-extra-v3/libmalcontent   0.11.1-2.1   0,20 MiB     0,04 MiB
cachyos-extra-v3/libsoup         2.74.3-1.1   2,68 MiB     0,46 MiB
cachyos-extra-v3/ostree          2023.3-1.1   4,41 MiB     0,81 MiB
cachyos-extra-v3/xdg-dbus-proxy  0.1.4-1.1    0,06 MiB     0,02 MiB
extra/flatpak                    1:1.15.4-1   6,89 MiB     1,76 MiB

Do pobrania:         3,12 MiB
Do zainstalowania:  14,31 MiB

:: Kontynuować instalację? [T/n] y
```
I assume this error is because console answer is hard-coded to "y"(yes), but this only works in ENG localisation. I have PL localisation and the correct answer to the above question from the console is "t"(Tak), not "y"(yes).

The solution to the above error would be, for example, waiting for the user to enter the answer, as is the case, when installing packages from the repository.

**Comment by vnepogodin** [comment]
I've removed that behavior in recent commit(https://github.com/CachyOS/packageinstaller/commit/3e249f79cc7df735fc138f18e98785e82ae05d1d)
