### ISSUE TITLE
libalpm.so.13 missing breaks installer

### ISSUE THREAD

**Issue by f1vefour** [CachyOS/packageinstaller#2]
I guess this is related to a pacman update but libalpm.so.13 is no longer on the system and is now libalpm.so.14, for the time being I linked 13 to 14 as a workaround but this needs to be fixed.

 `ln -s /usr/lib/libalpm.so.14.0.0 /usr/lib/libalpm.so.13`

I hope this is the correct git to report this issue as there is no git called cachyos-pi-launcher...

**Comment by TheWyn** [comment]
Can also confirm the issue on a new install

**Comment by ptr1337** [comment]
@vnepogodin

**Comment by ptr1337** [comment]
We will update it today.

**Comment by f1vefour** [comment]
Confirmed fixed.
