### ISSUE TITLE
CachyOS Package Installer not following system theme (KDE)

### ISSUE THREAD

**Issue by mdedetrich** [CachyOS/packageinstaller#3]
For some reason the CachyOS Package Installer is not following my system theme. I have the system theme currently set to Breeze (Dark), see screenshot for example

![image](https://github.com/CachyOS/packageinstaller/assets/2337269/cc503170-c4a6-4068-ab81-98977cffba0d)

As you can see, other Qt apps (such as Octopi) are working without issues. Do note I have the following

```
export QT_QPA_PLATFORMTHEME="qt5ct"
```

in `~/.profile`. Here are also the settings for Qt6 Settings app

![image](https://github.com/CachyOS/packageinstaller/assets/2337269/bbd9fa8d-b6a6-43c2-b25e-b7fcdc82605f)

**Comment by vnepogodin** [comment]
Because its running with root. If you start from CachyOS hello or with `sudo -E`
Then it will use your user configs/themes

**Comment by mdedetrich** [comment]
@vnepogodin This is indeed correct. Would it make sense to change it so that if you run CachyOS Package Installer via the KDE start menu that it doesn't' do it directly via root so it can use the user themes?

**Comment by vnepogodin** [comment]
> @vnepogodin This is indeed correct. Would it make sense to change it so that if you run CachyOS Package Installer via the KDE start menu that it doesn't' do it directly via root so it can use the user themes?

yeah I might work on it, that can be fixed by inheriting user config path(so $HOME).

Ideally that should be done so that app start only as user(inheriting all paths and themes)

**Comment by vnepogodin** [comment]
@mdedetrich should be fixed now also from KDE plasma menu.
update your system, which will install updated version 1.2.2

**Comment by mdedetrich** [comment]
> @mdedetrich should be fixed now also from KDE plasma menu. update your system, which will installed updated version 1.2.2

I can confirm its working, closing issue
